# Generated by Django 5.0.8 on 2024-08-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRegisterForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('interested_profile', models.CharField(max_length=100)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('previous_institute', models.CharField(max_length=150)),
                ('current_ctc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_ctc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], default='accepted', max_length=8)),
            ],
        ),
    ]
