# Generated by Django 5.0.8 on 2024-08-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_teacherregisterform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherregisterform',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], default='rejected', max_length=8),
        ),
    ]
