# Generated by Django 5.0.8 on 2024-08-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_course_learning_prerequisite_tag_usercourse_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prerequisite',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='video',
            name='course',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='user',
        ),
        migrations.DeleteModel(
            name='Learning',
        ),
        migrations.DeleteModel(
            name='Prerequisite',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='UserCourse',
        ),
    ]
